/// Flutter icons IconsDart
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsDart
///      fonts:
///       - asset: fonts/IconsDart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsDart {
  IconsDart._();

  static const _kFontFam = 'IconsDart';
  static const String? _kFontPkg = null;

  static const IconData shape = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
